apiVersion: v1
kind: Service
metadata:
  annotations:
   serviceloadbalancer/lb.host: "fileserver.wso2localapps.com"
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: file-server
    exposure-level: public
  name: file-server
  namespace: kube-system
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    name: file-server