apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influxdb
  name: influxdb
  namespace: kube-heapster
spec:
  replicas: 1
  selector:
    name: influxdb
  template:
    metadata:
      labels:
        name: influxdb
    spec:
      nodeSelector:
        role: loadbalancer
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.5
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        hostPath:
          path: /mnt/influxdb/data
