apiVersion: v1
kind: Service
metadata:
  annotations:
   serviceloadbalancer/lb.host: "mgtapp.wso2localapps.com"
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: mgt-app
    exposure-level: public
  name: mgt-app
  namespace: kube-system
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: mgt-app
